### ISSUE TITLE
Bug when using multiple or maxItens

### ISSUE THREAD

**Issue by nerijunior** [rhyek/vue2-selectize#3]
After all I need to say that your implementation works fine with a single select but using the multiple option or `maxItens = 10` (ex) on `:settings` when you click at the option the browser crash.

**Comment by mofman** [comment]
Is there a fix for this yet? essentially when you pass  maxItems = 1 and then select an option it crashes

**Comment by mofman** [comment]
Just noticed if I dont include a model with the field this works fine, I've tried using a string, array and object

**Comment by mofman** [comment]
issue is 

```
    setValue() {
      this.$el.selectize.setValue(this.value)
    }
```

**Comment by rhyek** [comment]
Hey, haven't really had time to check into this. If you're able to provide
a pull request with a fix, I'd be happy to merge.

On Jun 30, 2017 6:38 AM, "Andrew Moffett" <notifications@github.com> wrote:

issue is

    setValue() {
      this.$el.selectize.setValue(this.value)
    }

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rhyek/vue2-selectize/issues/3#issuecomment-312256273>,
or mute the thread

**Comment by rhyek** [comment]
This is now fixed with `1.1.0`. Be aware that I am now wrapping the component with a `<div>`.

**Comment by rhyek** [comment]
Nevermind about the `<div>`. Reverted with `1.1.1`.

**Comment by mofman** [comment]
Nice work on this, thanks
